#!/usr/bin/env tsx
/**
 * Weekly Report Generator
 * Generates weekly progress reports from GitHub data
 */

import { Octokit } from '@octokit/rest';

const octokit = new Octokit({
  auth: process.env.GITHUB_TOKEN,
});

const owner = process.env.GITHUB_OWNER || process.env.GITHUB_REPOSITORY?.split('/')[0] || '';
const repo = process.env.GITHUB_REPO || process.env.GITHUB_REPOSITORY?.split('/')[1] || '';

interface WeeklyStats {
  issuesOpened: number;
  issuesClosed: number;
  prsOpened: number;
  prsMerged: number;
  commits: number;
  contributors: Set<string>;
}

async function getWeeklyStats(): Promise<WeeklyStats> {
  const oneWeekAgo = new Date();
  oneWeekAgo.setDate(oneWeekAgo.getDate() - 7);
  const since = oneWeekAgo.toISOString();

  const stats: WeeklyStats = {
    issuesOpened: 0,
    issuesClosed: 0,
    prsOpened: 0,
    prsMerged: 0,
    commits: 0,
    contributors: new Set(),
  };

  // Get issues
  const issues = await octokit.issues.listForRepo({
    owner,
    repo,
    state: 'all',
    since,
    per_page: 100,
  });

  for (const issue of issues.data) {
    if (!issue.pull_request) {
      if (new Date(issue.created_at) >= oneWeekAgo) {
        stats.issuesOpened++;
      }
      if (issue.closed_at && new Date(issue.closed_at) >= oneWeekAgo) {
        stats.issuesClosed++;
      }
    }
  }

  // Get PRs
  const prs = await octokit.pulls.list({
    owner,
    repo,
    state: 'all',
    sort: 'updated',
    direction: 'desc',
    per_page: 100,
  });

  for (const pr of prs.data) {
    if (new Date(pr.created_at) >= oneWeekAgo) {
      stats.prsOpened++;
      if (pr.user) {
        stats.contributors.add(pr.user.login);
      }
    }
    if (pr.merged_at && new Date(pr.merged_at) >= oneWeekAgo) {
      stats.prsMerged++;
    }
  }

  // Get commits
  try {
    const commits = await octokit.repos.listCommits({
      owner,
      repo,
      since,
      per_page: 100,
    });

    stats.commits = commits.data.length;
    for (const commit of commits.data) {
      if (commit.author) {
        stats.contributors.add(commit.author.login);
      }
    }
  } catch {
    // Repository might be empty
  }

  return stats;
}

function generateReport(stats: WeeklyStats): string {
  const now = new Date();
  const weekStart = new Date(now);
  weekStart.setDate(weekStart.getDate() - 7);

  return `# 📊 Weekly Report

**Period:** ${weekStart.toLocaleDateString()} - ${now.toLocaleDateString()}

## Summary

| Metric | Count |
|--------|-------|
| Issues Opened | ${stats.issuesOpened} |
| Issues Closed | ${stats.issuesClosed} |
| PRs Opened | ${stats.prsOpened} |
| PRs Merged | ${stats.prsMerged} |
| Commits | ${stats.commits} |
| Contributors | ${stats.contributors.size} |

## Velocity

- **Issue Close Rate:** ${stats.issuesOpened > 0 ? Math.round((stats.issuesClosed / stats.issuesOpened) * 100) : 0}%
- **PR Merge Rate:** ${stats.prsOpened > 0 ? Math.round((stats.prsMerged / stats.prsOpened) * 100) : 0}%

## Contributors

${Array.from(stats.contributors).map((c) => `- @${c}`).join('\n') || '- No contributors this week'}

---
*Generated by [Weekly Report](../scripts/weekly-report.ts)*`;
}

async function createReportIssue(report: string): Promise<void> {
  const now = new Date();
  const title = `📊 Weekly Report - ${now.toLocaleDateString()}`;

  await octokit.issues.create({
    owner,
    repo,
    title,
    body: report,
    labels: ['📚 type:docs', '📊 priority:P3-Low'],
  });

  console.log(`✅ Created weekly report issue: ${title}`);
}

async function main() {
  console.log('📊 Generating weekly report...');

  try {
    const stats = await getWeeklyStats();
    const report = generateReport(stats);

    console.log('\n' + report);

    // Create issue with report
    await createReportIssue(report);
  } catch (error) {
    console.error('❌ Error generating report:', error);
    process.exit(1);
  }
}

main();
